### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by stephenway** [beville/ComicStreamer#3]
I would like to propose a new fresh design for this app's web interface.
The focus would be on usability, and simplified navigation.
This is just the start but I'll be committing a lot of front-end enhancements to my fork very soon.
![prototype](https://cloud.githubusercontent.com/assets/38894/3408002/671d0e4e-fdbe-11e3-91b0-bc6946d549a5.png)

![home sketch](https://cloud.githubusercontent.com/assets/38894/3408212/2b7699aa-fdc3-11e3-932e-9b2d500ef96c.jpg)

![navigation](https://cloud.githubusercontent.com/assets/38894/3408213/3529619e-fdc3-11e3-9c48-7c00cda970c3.jpg)

@beville Would love to pick your brain on the future of this project. Thanks

**Comment by kristinkrantz** [comment]
:+1:

**Comment by mike-ferenduros** [comment]
Looks really nice.
Any thoughts on what tapping a cover should do? Currently it goes straight to the reader, whereas it's be nice to have the option to see more metadata (including links to series, creators etc), and download or read.

**Comment by stephenway** [comment]
@mike-ferenduros Ideally it would be nice to get more info before reading. Lots of options we could provide with that detail view.

**Comment by beville** [comment]
Steven, this looks great! 

One note is that another guy, @brs165, has started on a presentation re-work using the bootstrap framework.  I'm not sure how far he's gotten since his last commit, but maybe you guys could join forces.  Alternatively, two independent visions might be pretty cool too.

My main desires/needs are:
- Apart from the configuration and control pages, I'd like the web UI to rely on the public API. This includes all pages that browse, search, and display comic metadata and the comic pages themselves. That would make web UI development relatively stand-alone.  The current HTML has some reliance on Tornado templates that I'd like to eliminate as much as possible.  If you have any need for new API features, just let me know.
- I want the UI to work for both desktop and touch/mobile interfaces.  This would be for both the library navigation and the reader.  The reader app that I incorporated in is pretty awesome (https://github.com/balaclark/HTML5-Comic-Book-Reader), but the main branch right now doesn't work well with my iPad, for example.  There is a branch for touch, but I haven't played with it yet.  I've added a number of feature requests on the issues page there.

The only main new features I'm thinking about for the near future is allowing for favorites (i.e. marking a comics as a favorite), and creating reading lists.  These would both have ramifications for UI design, as you'd want to select and mark books somehow.  Just something to keep in mind.

**Comment by stephenway** [comment]
Hey @beville, thanks for the feedback!

> I'd like the web UI to rely on the public API.

Looking through the templates I'm not sure I recognize what is using tornado, could you provide an example? I mostly just see the handlebars objects. Some documentation on the API would be helpful in this process, but I understand if that won't come till later.

> I want the UI to work for both desktop and touch/mobile interfaces.

There isn't anything I make that doesn't work responsively, however I think the reader is awesome but it does need a rewrite to be responsive from what I can tell.

I'll try to commit something soon, just got the sections on the index touch friendly.

**Comment by beville** [comment]
In index.html you'll find quite a bit of the Tornado-specific template code.  It usually starts with "{{" or "{%"

The Tornado docs are here:  http://www.tornadoweb.org/en/stable/template.html

So for example, where I've currently got the server providing the object for the random comic here:
https://github.com/beville/ComicStreamer/blob/master/comicstreamerlib/server.py#L891

and the HTML that renders it here:
https://github.com/beville/ComicStreamer/blob/master/comicstreamerlib/templates/index.html#L94

It would probably be better to de-couple that, and have the web page perform the query itself. In this example, page could get a comic list with a random offset and page size of 1.

Sounds cool, I'm looking forward to seeing your work!
